<!-- Задание 1.
Используя технологию R Markdown создайте динамический документ с
произвольными расчетами. Документ должен содержать вставки кода по типу inline и в виде
чанков. В документе должно быть использовано различное форматирование. Также для
оформления используйте каскадную таблицу стилей. Итоговый документ конвертируйте в
html формат и представьте в отчете, соответствующие скрины -->

---
title: "main"
author: "The Fool"
date: "2025-10-13"
output:
  html_document:
    css: style.css
---

## Практическая часть

Создадим случайные данные и выполним несколько вычислений.

```{r data, echo=TRUE}
set.seed(42)
x <- rnorm(100, mean = 50, sd = 10)
mean_x <- mean(x)
sd_x <- sd(x)
```

Температуру можно перевести из Кельвинов в Цельсии по формуле:

$$
C = K - 273.15
$$

Среднее значение выборки: **`r round(mean_x, 2)`**  
Стандартное отклонение: **`r round(sd_x, 2)`**

```{r hist, echo=FALSE}
hist(x,
     main = "Гистограмма случайных данных",
     xlab = "Значения X",
     col = "skyblue",
     border = "white")
```